# Generated by Django 4.1.1 on 2022-09-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khoja', '0002_alter_category_options_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
